import { Component, signal, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

interface Beneficio {
  nombre: string;
  logo: string;
  descripcionHtml: string;
}

@Component({
  selector: 'app-beneficios-comerciales',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './beneficios-comerciales.component.html',
  styleUrls: ['./beneficios-comerciales.component.scss']
})
export class BeneficiosComercialesComponent {
  modalActivo = signal<Beneficio | null>(null);

  beneficios: Beneficio[] = [
    { nombre: 'O2 Fitness', logo: 'images/beneficios-comerciales/o2.png', descripcionHtml: `<p>El gimnasio O2 Fitness (Vicealmirante O´connor 817, Bariloche) ofrece a nuestros socios un 10% de descuento en el abono mensual, abonando en efectivo o por transferencia.</p><p>Por consultas, podés contactarte por Instagram: @o2fitness.brc</p>` },
    { nombre: 'Allu', logo: 'images/beneficios-comerciales/allu.png', descripcionHtml: `<p><strong>¡Mantené tus tablas en excelente estado!</strong></p><p>ALLU ofrece un 20% de descuento para nuestros socios en la compra de ceras y herramientas de la marca.</p><p><em>Consultas y pedidos vía Instagram @alluargentina / o Whatsapp al (+54 9) 11 5925 5089.</em></p><p>Importante: Este beneficio no es acumulable con otras promociones, y es válido para pagos mediante transferencia.</p><p>El envío queda a cargo del comprador.</p><p>Promoción válida para socios AADIDESS, presentando credencial de socio al día.</p>` },
    { nombre: 'Interassist', logo: 'images/beneficios-comerciales/interassist.png', descripcionHtml: `<p>Si sos socio de AADIDESS y estás planeando viajar al exterior, este beneficio es para vos!</p><p><a href="https://www.instagram.com/interassist/">@interassist</a> te acerca este beneficio con una cobertura a un valor promocional.</p><p>Anual multiviaje, larga estadía por 120 días:<br><strong>Internacional: Tope de USD 200.000</strong>.- y <strong>Nacional: Tope USD 10.000.-</strong></p><p>Indemnización complementaria por pérdida de equipaje de Ski/Snowboard</p><p><strong>Forma de Pago:</strong></p><ul><li>En un pago por transferencia: U$S 1.570.-</li><li>En 6 cuotas sin interés de U$S 328,33 por cuota – Precio neto: U$D 1.970.-</li></ul><p><strong>Ponete en contacto para acceder a esta oportunidad de cobertura única.</strong></p><p>E-mail: <strong>venta.directa@interassist.travel</strong></p><p>Whatsapp: <strong>+54 9 11 6198-5594</strong><br>Horario de atención: <strong>De 8 hs a 22 hs los 7 días de la semana.</strong></p><p><strong><em>Importante: Beneficio válido para socios de hasta 50 años de edad.</em></strong></p>` },
    { nombre: 'Bataleón Latinoamérica', logo: 'images/beneficios-comerciales/bataleon.png', descripcionHtml: `<p>Bataleón Latinoamérica ofrece <strong>25% de descuento</strong> exclusivo para los socios de AADIDESS en tablas, botas y fijaciones.</p><p>Este beneficio aplica sobre el precio final IVA incluído.</p>` },
    { nombre: 'MACRO SELECTA', logo: 'svgs/banco-macro.svg', descripcionHtml: `<p>Hasta 12 cuotas sin interés con tarjetas de crédito Visa Signature Macro Selecta, <strong>del 24/06/2025 al 30/09/2025</strong> para pagos a través de Link de Pagos.</p><p>Se accede al beneficio solicitando el link de pago correspondiente, exclusivo para Macro Selecta.</p><p><strong>Válido para abonar cuota societaria, cursos y demás actividades aranceladas de la asociación.</strong></p>` },
    { nombre: 'Kine Sport PRO', logo: 'images/beneficios-comerciales/kine-sport-pro.png', descripcionHtml: `<p>Kinesport Pro ofrece un <strong>20% de descuento</strong> a nuestros socios en plantillas personalizadas de alto rendimiento.</p><p>Por consultas y turnos, comunicarse por Whatsapp al <strong>297241596.</strong></p>` },
    { nombre: 'OUTDOOR COMPANY', logo: 'images/beneficios-comerciales/outdoor-company.png', descripcionHtml: `<p><strong>Si necesitas equiparte para esta temporada, ¡este beneficio es para vos!</strong></p><p><a href="https://www.instagram.com/outdoorcompany/">Outdoor Company</a> ofrece a los socios AADIDESS un <strong>20% de descuento</strong> en compras en efectivo en el local de Catedral, presentando credencial al día.</p>` },
    { nombre: 'CP + 02 Fitness', logo: 'images/beneficios-comerciales/capacitaciones-profesionales-o2.png', descripcionHtml: `<p><strong>20% de descuento</strong> en el curso de Instructorado en Musculación y Preparación Física Integral en Capacitaciones Profesionales.</p><p><strong>¡Inscripciones abiertas!</strong></p><ul><li>Fecha de inicio: 28 de julio - Cupos limitados</li><li>Dictado por: Martin Ramos</li><li>Modalidad de cursada: híbrida (presencial en @o2fitnessbrc , en Bariloche, y online)</li></ul><p>Certificación avalada por el Ministerio de Educación de la Nación, el INEP (Universidad de Río Negro) y el Ises.</p><p><strong>Para más info e inscripciones ingresa a <a href="http://www.capacitacionesprofesionales.com.ar/">Campus Virtual</a> o escribinos a <a href="mailto:informes@capacitacionesprofesionales.com.ar">informes@capacitacionesprofesionales.com.ar</a></strong></p>` },
    { nombre: 'KODA', logo: 'images/beneficios-comerciales/koda.png', descripcionHtml: `<p>Si estas buscando equiparte para esta temporada, <a href="https://www.instagram.com/koda_outdoor/">@koda_outdoor</a> ofrece a todos nuestros socios un <strong>25% de descuentos en todos sus productos de la línea invierno</strong> (Antiparras, Cuellos, Pasamontañas, Gorros) pagando con transferencia. <strong>O pagando con tarjeta y en 3 cuotas sin interés, accedes a un 15% off</strong></p><p>Podes ver todos sus productos en: <a href="http://www.kodaoutdoor.com.ar/">Tienda Online de KODA OUTDOOR</a> o en su instagram <a href="https://www.instagram.com/koda_outdoor/">@koda_outdoor</a></p><p>Por consultas, podés comunicarte a <a href="mailto:oficial.kodaoutdoor@gmail.com">oficial.kodaoutdoor@gmail.com</a></p>` },
    { nombre: 'AMPLID', logo: 'images/beneficios-comerciales/amplid.png', descripcionHtml: `<p>Si estás buscando equiparte para esta temporada, Amplid Latin America ofrece a todos nuestros socios un <strong>15% de descuento sobre el precio final al público</strong> (I.V.A. incluído) en todos sus productos de la línea Amplid Snowboards (tablas, fijaciones y soft goods, solid boards, fijaciones, split boards amplid, remeras, gorros, balaclavas, mochilas). No incluye fijaciones SPARK ni Pieles de Kohla.</p><p>Podés ver todos los productos en su perfil de Instagram <a href="https://www.instagram.com/amplid.latinamerica/">@amplid.latinamerica</a> <em>(próximamente tienda online disponible).</em></p><p>Para hacer tu pedido, contáctate a <a href="mailto:sgraziosi@andespow.com">sgraziosi@andespow.com</a> o a <a href="mailto:info@andespow.com">info@andespow.com</a>.</p><p>Formas de pago: Depósito en cta cte / Mercadopago</p>` },
    { nombre: 'Hub Travel', logo: 'images/beneficios-comerciales/hub-travel.png', descripcionHtml: `<p><strong>Precios promocionales para socios.</strong></p><p>Atención y asesoramiento personalizado para encontrar la mejor opción para tu viaje.</p><p><strong>Contacto:</strong></p><p>11 5219 1414</p><p><a href="mailto:florencia@hubtravel.com.ar">florencia@hubtravel.com.ar</a></p>` },
    { nombre: 'Meridional Seguros', logo: 'images/beneficios-comerciales/meridional-seguros.png', descripcionHtml: `<p>Meridional Seguros ofrece para socios y cursantes una opción de cobertura por <strong>120 días.</strong></p><figure class="wp-block-image"><img loading="lazy" decoding="async" width="1024" height="628" src="https://aadidess.com/wp-content/uploads/2025/05/cuadromeridional-1024x628.png" alt=""></figure><p><strong>Contacto:</strong></p><p>Mitre 899 1° Piso S.C. Bariloche</p><p>294-4436678- 154587386</p><p><a href="mailto:organizacionbariloche@outlook.com">organizacionbariloche@outlook.com</a></p><p><a href="http://www.merdionalseguros.com.ar/" target="_blank" rel="noreferrer noopener">www.merdionalseguros.com.ar</a></p>` },
    { nombre: 'Medicus', logo: 'images/beneficios-comerciales/medicus.png', descripcionHtml: `<p><strong>Información no disponible.</strong></p><p><strong>Alejandro J. Moretton<br>Ejecutivo de Cuentas - Gcia. Comercial</strong></p><ul><li>Gobernador Quaglia 166, San Carlos de Bariloche</li><li>Whatsapp +542944804931</li></ul>` },
    { nombre: 'Move Sport Club', logo: 'images/beneficios-comerciales/move.png', descripcionHtml: `<p>Move Sport Club, en El Bolsón, ofrece un <strong>10% de descuento</strong> para socios AADIDESS en el abono mensual de gimnasio libre o con plan y en productos del shop.</p><p>Por consultas, comunicate al 2944629048 o vía mail a <a href="mailto:moveelbolson@gmail.com">moveelbolson@gmail.com</a><br>Dirección: 25 de mayo 3274, El Bolsón</p>` },
    { nombre: 'Swiss Medical', logo: 'images/beneficios-comerciales/swiss-medical.png', descripcionHtml: `<p>La misión definida por Swiss Medical Group es cuidar la salud de nuestros asociados brindando un servicio médico de excelencia.</p><p>Los beneficios aplican a nuevos asociados de Swiss Medical (no para quienes ya cuentan con la cobertura antes de ser socios de AADIDESS)</p><p><a href="https://dev.aadidess.com/wp-content/uploads/2025/07/Buenas_Noticias_Aadidess.pdf">VER MÁS DETALLE</a></p><p><strong>Swiss Medical Group</strong><br>Swiss Medical Medicina Privada España 286 | S.C. de Bariloche Tel: 0294 442-4200 Teléfono / Fax: 0294 442-4200</p><p><strong>Monica Russo:</strong> Asesora Comercial</p><p>294 4658361</p><p><a href="mailto:Monica.russo@swissmedical.com.ar">monica.russo@swissmedical.com.ar</a></p>` },
    { nombre: 'Andar Sports', logo: 'images/beneficios-comerciales/andar-sports.png', descripcionHtml: `<p><strong>Convenio AADIDESS</strong></p><p><strong>Andar Sports ofrece un 10% de descuento para los socios de AADIDESS, presentando su carnet vigente.</strong></p><p><strong>La promo incluye bootfitting y plantillas.</strong></p><p>Dirección C/Bonaventura Riberaygua 32, Andorra la Vella.</p><p><a href="https://www.andarsports.com/es/" target="_blank" rel="noreferrer noopener"><strong>www.andarsports.com/es/</strong></a></p>` },
    { nombre: 'Decorart', logo: 'images/beneficios-comerciales/decorart.png', descripcionHtml: `<p><strong>Convenio AADIDESS</strong></p><p>Decorart® se suma a los beneficios para los socios de la asociación.</p><p><strong>20% de descuento sobre precios de lista</strong> <strong>y hasta 3 cuotas sin interés con tarjeta de crédito</strong> en revestimientos (pisos, alfombras, cortinas, papeles, cielorrasos, toldos) para tu hogar y/o empresa. 50 años de experiencia en el mercado avalan la profesionalidad de DECORART®, que te ofrece atención personalizada para cada uno de tus proyectos.</p><p>Con base en La Plata realizan envíos a todo el país (no incluído en el descuento).</p><p>Podés acceder a su catálogo de productos en <strong><a href="http://www.decorart.com.ar/" target="_blank" rel="noreferrer noopener">www.decorart.com.ar</a></strong> o contactarte a:</p><p><strong>decorart@decorart.com.ar | 0221 422 6552 | Av 7 Nro. 404 esquina 40 (1900) La Plata</strong></p>` },
    { nombre: 'Kinetic Lab', logo: 'images/beneficios-comerciales/kinetic-lab.png', descripcionHtml: `<p>KineticLab Bariloche ofrece un 15% de descuento a instructores AADIDESS en el estudio de la marcha, la pisada y evaluación postural completo.</p><p>Consultas: 2944 390959</p>` },
    { nombre: 'Gimnasio ATP', logo: 'images/beneficios-comerciales/gimnasio-atp.png', descripcionHtml: `<p><strong>Convenio AADIDESS</strong></p><p>¡Entrenate en San Martín de los Andes!</p><p><strong>20% DE DESCUENTO</strong><br>En tu abono mensual, sobre precios de lista.</p><p>Pago contado, efectivo.</p><p>Promoción no acumulable con otros descuentos.</p><p>Válida hasta el 31-12-2019</p><p><strong>Contacto:</strong></p><p>e-mail: <a href="mailto:atpsmandes@gmail.com">atpsmandes@gmail.com</a><br>Dirección: Perito Moreno 937, San Martín de los Andes</p><p>Tel: 02972-429-592</p><p><em>*Promoción válida presentado tu credencial de socio de AADIDESS al día.</em></p>` },
    { nombre: 'Balanz', logo: 'images/beneficios-comerciales/balanz.png', descripcionHtml: `<p><strong>25% de Descuento en los gastos transaccionales en Balanz</strong></p><p>A través de Balanz pueden acceder a todos los instrumentos de inversión del mercado de capitales local e internacional. Incluye asesoramiento financiero personalizado por medio de Martín Quintiero Matriculado en CNV (Matrícula N° 1083)</p><p>Este descuento será otorgado en cada cuenta que ingrese siguiendo estos pasos:</p><ol><li>Descargar la app de Balanz en el celular.</li><li>Salir de la aplicación.</li><li>Ingresar el siguiente link <a href="https://bit.ly/3qbPGpR">https://bit.ly/3qbPGpR</a></li><li>Allí, cargar datos personales como nombre, apellido, mail personal.</li><li>Al mail indicado le llega un código para retomar la apertura desde la app donde podrá ingresar todos los datos personales completos + sacar foto de dni + selfie</li></ol><p>Apertura de cuentas locales sin costo de apertura y mantenimiento.</p><p>Contacto:</p><p>Martín Quintiero<br><a href="mailto:mquintiero@ap.balanz.com">mquintiero@ap.balanz.com</a></p><p>Tel.: +(5411) 7078-0815<br>Cel.: +52 1 984 191 1150</p><p><a href="https://www.balanz.com/" target="_blank" rel="noreferrer noopener">www.balanz.com</a></p><p><em>*Promoción válida para socios AADIDESS</em></p>` },
    { nombre: 'Salón Estético Unisex', logo: 'images/beneficios-comerciales/salon-estetico-unisex.png', descripcionHtml: `<p><strong>15% DE DESCUENTO</strong><br>Pago contado, débito, crédito y Mercado Pago.</p><p>Servicios: masaje reflexológico podal / pedicuría deportiva / manicuría / masajes faciales / cortes de cabello / barbería</p><p><strong>Contacto Carlos Roch:</strong></p><p>e-mail: <a href="mailto:cjroch@gmail.com">cjroch@gmail.com</a></p><p>Tel.: 294 436 5787<br>Dirección: Bo. Nuestra Señora de las Nieves, Calle de la Centella 13400 (altura Av. Bustillo KM 13), Bariloche</p><p>Gabinete en el centro de Bariloche: Calle Salta 331 Fit Soul</p><p><em>*Promoción válida presentado tu credencial de socio de AADIDESS al día.</em></p>` },
    { nombre: 'Travesía Sur Hostel', logo: 'images/beneficios-comerciales/travesia-sur-hostel.png', descripcionHtml: `<p>Travesía Sur Hostel ofrece un <strong>15 % de descuento</strong> para cursantes de AADIDESS y armado de paquetes para la temporada 2024.</p><p>Contacto: <strong>+54 9 2944 58-0850</strong><br><strong>Dorrego y Rivadavia (zona centro, El Bolsón)</strong></p>` },
    { nombre: 'Alaska Mountain', logo: 'images/beneficios-comerciales/alaska-mountain.png', descripcionHtml: `<p>Alaska Mountain, marca de indumentaria y productos para actividades outdoor ofrece un <strong>25% DE DESCUENTO</strong> a todos los socios de AADIDESS en compras online en <a href="http://www.alaskamtn.com/" target="_blank" rel="noreferrer noopener">www.alaskamtn.com</a>.</p><p>Para acceder a este beneficio, solicitá tu código a <a href="mailto:comunicacion@aadidess.com">comunicacion@aadidess.com</a> y aplicalo al momento de realizar el pedido en la web.</p><p>¡Aprovechalo y equipate con todo lo que necesitás para la montaña!</p><p>Este beneficio no es acumulable con otras promociones.</p>` },
    { nombre: 'Open English', logo: 'images/beneficios-comerciales/open-english.png', descripcionHtml: `<p>Hasta <strong>80% de descuento</strong> para socios de AADIDESS y familiares directos.</p><p><strong>Válido para cursos: Open English, Open English Junior y NEXTU</strong></p><ul><li>Acceso al curso las 24 horas del día, los 7 días de la semana.</li><li>Clases en vivo las 24 horas del día, cada 30 minutos todo el año.</li><li>Profesores nativos certificados por el ESL y TESOL.</li><li>Prácticas interactivas con contenidos específicos.</li><li>Territorio argentino</li><li>Descuento aplicable a los cursos sobre el precio de lista.</li><li>Línea de Servicio VIP (Equipo que se encargará de atender cualquier duda o inconveniente con la plataforma de forma personalizada y en horario extendido).</li></ul><p><strong>Para realizar consultas y/o acceder a este beneficio, comunicate con <a href="mailto:jimena.breide@openenglish.com">jimena.breide@openenglish.com</a></strong></p>` },
    { nombre: 'PARALELO 42', logo: 'images/beneficios-comerciales/paralelo42.png', descripcionHtml: `<p>Paralelo 42, Tienda de equipamiento para actividades al aire libre, ofrece a nuestros socios un <strong>20% de descuento</strong> en compras realizadas en efectivo, y <strong>5% de descuento</strong> en compras con tarjetas.<br><strong>Dirección: Sarmiento 775, Esquel.</strong></p>` }
  ];

  abrirModal(beneficio: Beneficio): void {
    this.modalActivo.set(beneficio);
    document.body.style.overflow = 'hidden';
  }

  cerrarModal(): void {
    this.modalActivo.set(null);
    document.body.style.overflow = '';
  }

  @HostListener('document:keydown.escape')
  onEscape() {
    if (this.modalActivo()) {
      this.cerrarModal();
    }
  }
}